const customers = [
  {
    "customerID": "ALFKI",
    "companyName": "Alfreds Futterkiste",
    "contactName": "Maria Anders",
    "contactTitle": "Sales Representative",
    "address": "Obere Str. 57",
    "city": "Berlin",
    "region": null,
    "postalCode": "12209",
    "country": "Germany",
    "phone": "030-0074321",
    "fax": "030-0076545"
  },
  
  {
    "customerID": "REGGC",
    "companyName": "Reggiani Caseifici",
    "contactName": "Maurizio Moroni",
    "contactTitle": "Sales Associate",
    "address": "Strada Provinciale 124",
    "city": "Reggio Emilia",
    "region": null,
    "postalCode": "42100",
    "country": "Italy",
    "phone": "0522-556721",
    "fax": "0522-556722"
  },
  {
    "customerID": "RICAR",
    "companyName": "Ricardo Adocicados",
    "contactName": "Janete Limeira",
    "contactTitle": "Assistant Sales Agent",
    "address": "Av. Copacabana 267",
    "city": "Rio de Janeiro",
    "region": "RJ",
    "postalCode": "02389-890",
    "country": "Brazil",
    "phone": "(21) 555-3412",
    "fax": null
  },
  {
    "customerID": "RICSU",
    "companyName": "Richter Supermarkt",
    "contactName": "Michael Holz",
    "contactTitle": "Sales Manager",
    "address": "Grenzacherweg 237",
    "city": "Genève",
    "region": null,
    "postalCode": "1203",
    "country": "Switzerland",
    "phone": "0897-034214",
    "fax": null
  },
  {
    "customerID": "ROMEY",
    "companyName": "Romero y tomillo",
    "contactName": "Alejandra Camino",
    "contactTitle": "Accounting Manager",
    "address": "Gran Vía 1",
    "city": "Madrid",
    "region": null,
    "postalCode": "28001",
    "country": "Spain",
    "phone": "(91) 745 6200",
    "fax": "(91) 745 6210"
  },
  {
    "customerID": "SANTG",
    "companyName": "Santé Gourmet",
    "contactName": "Jonas Bergulfsen",
    "contactTitle": "Owner",
    "address": "Erling Skakkes gate 78",
    "city": "Stavern",
    "region": null,
    "postalCode": "4110",
    "country": "Norway",
    "phone": "07-98 92 35",
    "fax": "07-98 92 47"
  },
  {
    "customerID": "SAVEA",
    "companyName": "Save-a-lot Markets",
    "contactName": "Jose Pavarotti",
    "contactTitle": "Sales Representative",
    "address": "187 Suffolk Ln.",
    "city": "Boise",
    "region": "ID",
    "postalCode": "83720",
    "country": "USA",
    "phone": "(208) 555-8097",
    "fax": null
  },
  {
    "customerID": "SEVES",
    "companyName": "Seven Seas Imports",
    "contactName": "Hari Kumar",
    "contactTitle": "Sales Manager",
    "address": "90 Wadhurst Rd.",
    "city": "London",
    "region": null,
    "postalCode": "OX15 4NB",
    "country": "UK",
    "phone": "(171) 555-1717",
    "fax": "(171) 555-5646"
  },
  {
    "customerID": "SIMOB",
    "companyName": "Simons bistro",
    "contactName": "Jytte Petersen",
    "contactTitle": "Owner",
    "address": "Vinbæltet 34",
    "city": "Kobenhavn",
    "region": null,
    "postalCode": "1734",
    "country": "Denmark",
    "phone": "31 12 34 56",
    "fax": "31 13 35 57"
  },
  {
    "customerID": "SPECD",
    "companyName": "Spécialités du monde",
    "contactName": "Dominique Perrier",
    "contactTitle": "Marketing Manager",
    "address": "25 rue Lauriston",
    "city": "Paris",
    "region": null,
    "postalCode": "75016",
    "country": "France",
    "phone": "(1) 47.55.60.10",
    "fax": "(1) 47.55.60.20"
  },
  {
    "customerID": "SPLIR",
    "companyName": "Split Rail Beer & Ale",
    "contactName": "Art Braunschweiger",
    "contactTitle": "Sales Manager",
    "address": "P.O. Box 555",
    "city": "Lander",
    "region": "WY",
    "postalCode": "82520",
    "country": "USA",
    "phone": "(307) 555-4680",
    "fax": "(307) 555-6525"
  },
  {
    "customerID": "SUPRD",
    "companyName": "Suprêmes délices",
    "contactName": "Pascale Cartrain",
    "contactTitle": "Accounting Manager",
    "address": "Boulevard Tirou 255",
    "city": "Charleroi",
    "region": null,
    "postalCode": "B-6000",
    "country": "Belgium",
    "phone": "(071) 23 67 22 20",
    "fax": "(071) 23 67 22 21"
  },
  {
    "customerID": "THEBI",
    "companyName": "The Big Cheese",
    "contactName": "Liz Nixon",
    "contactTitle": "Marketing Manager",
    "address": "89 Jefferson Way Suite 2",
    "city": "Portland",
    "region": "OR",
    "postalCode": "97201",
    "country": "USA",
    "phone": "(503) 555-3612",
    "fax": null
  },
  {
    "customerID": "THECR",
    "companyName": "The Cracker Box",
    "contactName": "Liu Wong",
    "contactTitle": "Marketing Assistant",
    "address": "55 Grizzly Peak Rd.",
    "city": "Butte",
    "region": "MT",
    "postalCode": "59801",
    "country": "USA",
    "phone": "(406) 555-5834",
    "fax": "(406) 555-8083"
  },
  {
    "customerID": "TOMSP",
    "companyName": "Toms Spezialitäten",
    "contactName": "Karin Josephs",
    "contactTitle": "Marketing Manager",
    "address": "Luisenstr. 48",
    "city": "Münster",
    "region": null,
    "postalCode": "44087",
    "country": "Germany",
    "phone": "0251-031259",
    "fax": "0251-035695"
  },
  {
    "customerID": "TORTU",
    "companyName": "Tortuga Restaurante",
    "contactName": "Miguel Angel Paolino",
    "contactTitle": "Owner",
    "address": "Avda. Azteca 123",
    "city": "México D.F.",
    "region": null,
    "postalCode": "05033",
    "country": "Mexico",
    "phone": "(5) 555-2933",
    "fax": null
  },
  {
    "customerID": "TRADH",
    "companyName": "Tradição Hipermercados",
    "contactName": "Anabela Domingues",
    "contactTitle": "Sales Representative",
    "address": "Av. Inês de Castro 414",
    "city": "Sao Paulo",
    "region": "SP",
    "postalCode": "05634-030",
    "country": "Brazil",
    "phone": "(11) 555-2167",
    "fax": "(11) 555-2168"
  },
  {
    "customerID": "TRAIH",
    "companyName": "Trail's Head Gourmet Provisioners",
    "contactName": "Helvetius Nagy",
    "contactTitle": "Sales Associate",
    "address": "722 DaVinci Blvd.",
    "city": "Kirkland",
    "region": "WA",
    "postalCode": "98034",
    "country": "USA",
    "phone": "(206) 555-8257",
    "fax": "(206) 555-2174"
  },
  {
    "customerID": "VAFFE",
    "companyName": "Vaffeljernet",
    "contactName": "Palle Ibsen",
    "contactTitle": "Sales Manager",
    "address": "Smagsloget 45",
    "city": "Århus",
    "region": null,
    "postalCode": "8200",
    "country": "Denmark",
    "phone": "86 21 32 43",
    "fax": "86 22 33 44"
  },
  {
    "customerID": "VICTE",
    "companyName": "Victuailles en stock",
    "contactName": "Mary Saveley",
    "contactTitle": "Sales Agent",
    "address": "2 rue du Commerce",
    "city": "Lyon",
    "region": null,
    "postalCode": "69004",
    "country": "France",
    "phone": "78.32.54.86",
    "fax": "78.32.54.87"
  },
  {
    "customerID": "VINET",
    "companyName": "Vins et alcools Chevalier",
    "contactName": "Paul Henriot",
    "contactTitle": "Accounting Manager",
    "address": "59 rue de l'Abbaye",
    "city": "Reims",
    "region": null,
    "postalCode": "51100",
    "country": "France",
    "phone": "26.47.15.10",
    "fax": "26.47.15.11"
  },
  {
    "customerID": "WANDK",
    "companyName": "Die Wandernde Kuh",
    "contactName": "Rita Müller",
    "contactTitle": "Sales Representative",
    "address": "Adenauerallee 900",
    "city": "Stuttgart",
    "region": null,
    "postalCode": "70563",
    "country": "Germany",
    "phone": "0711-020361",
    "fax": "0711-035428"
  },
  {
    "customerID": "WARTH",
    "companyName": "Wartian Herkku",
    "contactName": "Pirkko Koskitalo",
    "contactTitle": "Accounting Manager",
    "address": "Torikatu 38",
    "city": "Oulu",
    "region": null,
    "postalCode": "90110",
    "country": "Finland",
    "phone": "981-443655",
    "fax": "981-443655"
  },
  {
    "customerID": "WELLI",
    "companyName": "Wellington Importadora",
    "contactName": "Paula Parente",
    "contactTitle": "Sales Manager",
    "address": "Rua do Mercado 12",
    "city": "Resende",
    "region": "SP",
    "postalCode": "08737-363",
    "country": "Brazil",
    "phone": "(14) 555-8122",
    "fax": null
  },
  {
    "customerID": "WHITC",
    "companyName": "White Clover Markets",
    "contactName": "Karl Jablonski",
    "contactTitle": "Owner",
    "address": "305 - 14th Ave. S. Suite 3B",
    "city": "Seattle",
    "region": "WA",
    "postalCode": "98128",
    "country": "USA",
    "phone": "(206) 555-4112",
    "fax": "(206) 555-4115"
  },
  {
    "customerID": "WILMK",
    "companyName": "Wilman Kala",
    "contactName": "Matti Karttunen",
    "contactTitle": "Owner/Marketing Assistant",
    "address": "Keskuskatu 45",
    "city": "Helsinki",
    "region": null,
    "postalCode": "21240",
    "country": "Finland",
    "phone": "90-224 8858",
    "fax": "90-224 8858"
  },
  {
    "customerID": "WOLZA",
    "companyName": "Wolski  Zajazd",
    "contactName": "Zbyszek Piestrzeniewicz",
    "contactTitle": "Owner",
    "address": "ul. Filtrowa 68",
    "city": "Warszawa",
    "region": null,
    "postalCode": "01-012",
    "country": "Poland",
    "phone": "(26) 642-7012",
    "fax": "(26) 642-7012"
  }
 ]

 export default customers;